### ISSUE TITLE
Support for Python 3.7 and 3.8

### ISSUE THREAD

**Issue by svisser** [timhutton/twitter-archive-parser#49]
For anyone running Python 3.8 and below, the script now fails with:

```
Parsing ./data/tweets.js...
Traceback (most recent call last):
  File "parser.py", line 176, in <module>
    main()
  File "parser.py", line 148, in main
    tweets_markdown += [tweet_json_to_markdown(tweet, username, archive_media_folder, output_media_folder_name) for tweet in json]
  File "parser.py", line 148, in <listcomp>
    tweets_markdown += [tweet_json_to_markdown(tweet, username, archive_media_folder, output_media_folder_name) for tweet in json]
  File "parser.py", line 62, in tweet_json_to_markdown
    body = body.removeprefix(replying_to)
AttributeError: 'str' object has no attribute 'removeprefix'
```

The `.removeprefix(..)` string method was introduced in Python 3.9 ([changelog](https://docs.python.org/3/whatsnew/3.9.html#new-string-methods-to-remove-prefixes-and-suffixes)).

It might be nice to also support Python 3.7 and 3.8 to reduce any hassle with not running a particular version of Python 3. Alternatively, it could be mentioned in the README that Python 3.9+ is expected but personally I feel it's better to make it work for those Python releases.

**Comment by svisser** [comment]
To add: I mentioned 3.7 and 3.8 because those have not yet reached end of life (https://endoflife.date/python).
