### ISSUE TITLE
name 'media_sources' is not defined

### ISSUE THREAD

**Issue by stuffmc** [timhutton/twitter-archive-parser#89]
```
The archive doesn't contain the original-size images. We can attempt to download them from twimg.com.
Please be aware that this script may download a lot of data, which will cost you money if you are
paying for bandwidth. Please be aware that the servers might block these requests if they are too
frequent. This script may not work if your account is protected. You may want to set it to public
before starting the download.

OK to start downloading? [y/n]y
Traceback (most recent call last):
  File "~/Downloads/twitter-2022-11-01-b470d4ee7c7ba96e09a7782d4451d9c6852c3d7322cdcf3a91dbe40943586323/parser.py", line 580, in <module>
    main()
  File "~/Downloads/twitter-2022-11-01-b470d4ee7c7ba96e09a7782d4451d9c6852c3d7322cdcf3a91dbe40943586323/parser.py", line 575, in main
    download_larger_media(media_sources, log_path)
NameError: name 'media_sources' is not defined
```

**Comment by timhutton** [comment]
Thank you for reporting! I'll fix this.

**Comment by SerenadeX** [comment]
Seeing the same thing

**Comment by timhutton** [comment]
Should be fixed now. Please try with the latest version and reopen this issue if not.

**Comment by stuffmc** [comment]
Wow. https://gruene.social/@manu/109377096279023873
